#spring.datasource.url=jdbc:postgresql://localhost:5432/<YOUR_DATABASE_NAME>
#spring.datasource.username=<YOUR_USERNAME>
#spring.datasource.password=<YOUR_PASSWORD>
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
# Web
spring.threads.virtual.enabled=true
# Database
#spring.datasource.url=jdbc:h2:mem:dcbapp
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=user
#spring.datasource.password=password
# Database (JPA)
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
# Database (H2)
spring.h2.console.enabled=false
#
#spring.artemis.mode=native
#spring.artemis.broker-url=tcp://192.168.1.210:9876
#spring.artemis.user=admin
#spring.artemis.password=secret
#
#spring.jmx.enabled=true
#
#hawtio.authenticationEnabled=false