<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.f442y.dispersion.orchestration</groupId>
        <artifactId>sample</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.github.f442y.dispersion.orchestration.sample</groupId>
    <artifactId>sample-orchestration-entities</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.github.f442y.dispersion.orchestration</groupId>
            <artifactId>orchestrator-entity-interfaces</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.f442y.dispersion.orchestration.spi.entities</groupId>
            <artifactId>SampleOE</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.github.f442y.dispersion.core</groupId>
            <artifactId>database-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>